<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\IntelliImport.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\IntelliImport.Infrastructure.csproj" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="MediatR"                Version="12.4.0" />
  </ItemGroup>
</Project>
